# Generated by Django 5.0.4 on 2024-05-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id_catalog', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('cathegorie', models.CharField(max_length=150)),
            ],
        ),
    ]
