# Generated by Django 5.0.4 on 2024-05-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_catalog', models.CharField(max_length=25)),
                ('cathegorie', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='photo',
            name='caption',
        ),
    ]
