# Generated by Django 5.0.4 on 2024-06-26 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0003_alter_blog_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_boutique', models.CharField(max_length=128)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('adresse', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=14)),
                ('ville', models.CharField(max_length=155)),
                ('pays', models.CharField(max_length=155)),
                ('description', models.TextField(max_length=500)),
                ('starred', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Articles.photo')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cathegorie', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cathegorie', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(max_length=120)),
                ('quantite', models.IntegerField(max_length=50)),
                ('prix', models.FloatField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
        migrations.AddField(
            model_name='boutique',
            name='cathegorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.catalogboutique'),
        ),
        migrations.AddField(
            model_name='produit',
            name='boutique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.boutique'),
        ),
        migrations.AddField(
            model_name='produit',
            name='cathegorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.catalogproduit'),
        ),
        migrations.AddField(
            model_name='produit',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Articles.photo'),
        ),
    ]
