# Generated by Django 5.1.1 on 2025-03-13 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0004_boutique_catalogboutique_catalogproduit_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='nom_boutique',
            field=models.CharField(max_length=128, verbose_name='Nom de la boutique'),
        ),
        migrations.CreateModel(
            name='CarouselPhotoDescriptio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=50)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Articles.photo')),
            ],
        ),
    ]
