# Generated by Django 5.1.1 on 2025-03-13 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0005_alter_boutique_nom_boutique_carouselphotodescriptio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarouselPhotoDescriptio',
            new_name='CarouselPhotoDescription',
        ),
    ]
