# Generated by Django 5.1.1 on 2025-03-16 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0006_rename_carouselphotodescriptio_carouselphotodescription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commander', models.BooleanField(default=False)),
                ('date_commande', models.DateField(blank=True, null=True)),
                ('articles', models.ManyToManyField(to='Articles.produit', verbose_name='Articles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
