# Generated by Django 3.2.23 on 2024-04-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
